### ISSUE TITLE
[Frontend/Backend-Dashboard] Tables

### ISSUE THREAD

**Issue by LuckyShuii** [WildCodeSchool/2024-02-wns-bleu-wetransfer#16]
### Narration

- En tant qu'utilisateur je veux avoir accès à tous mes fichiers afin de mieux visualiser tout ce que j'ai de stocké et partagé
- En tant qu'utilisateur je veux voir à qui j'ai partagé mes fichiers afin de me souvenir qui y à accès
- En tant qu'utilisateur je veux pouvoir effectuer des actions sur mes fichiers afin de pouvoir les supprimer et autres pour libérer de l'espace par exemple
- En tant qu'utilisateur je veux pouvoir gérer les personnes à qui j'ai partagé mes fichiers afin de supprimer ou ajouter des personnes facilement pour voir mes fichiers

### Spec

- [ ] Both tables on the image are one unique table with 2 different view depending the chosen view in the above button
- [ ] All buttons are working
- [ ] Share feature works, no emailing at the moment required
- [ ] The edit button should allow the user to edit the file name of the row
- [ ] When selecting multiple files, the top button to shares a selection of files should go from disabled to not disabled

### Hors scope

- Upload file system front/back
- Header
- Other part of the dashboard which are not related to the tables

### SubTask
- For the column "Shared with", check the select component from Ant Design and adapt it, its not properly shown on the mockup

### Critère d'acceptante

- [ ] When choosing different view of the table, the data changes in the table changes
- [ ] All action buttons working
- [ ] Share a file with someone is working (no emailing yet required)
- [ ] The edit button allows the user to edit the file name

### Images

![Image](https://github.com/WildCodeSchool/2024-02-wns-bleu-wetransfer/assets/25879136/4fba8a91-3d80-4b67-8076-1c4d9a666bda)
